#!/usr/bin/env python3
"""Generate src/transport/RootCABundle.h from a current Mozilla CA bundle.

Why this exists: baking a fixed CA bundle into the library source is an
anti-pattern (roots rotate; stale bundles silently break TLS). Instead we keep
the bundle out of source and regenerate it on demand from the canonical Mozilla
set published at https://curl.se/ca/cacert.pem.

Usage:
    python3 tools/gen_ca_bundle.py            # download and embed the full set
    python3 tools/gen_ca_bundle.py --file x.pem   # use a local PEM instead

The full Mozilla bundle is ~200 KB of flash. For tight boards (ESP8266) you may
prefer to pass a --file containing only the single root your provider uses.
"""

import argparse
import sys
import urllib.request
from datetime import datetime, timezone

DEFAULT_URL = "https://curl.se/ca/cacert.pem"
OUTPUT_PATH = "src/transport/RootCABundle.h"


def load_pem(args: argparse.Namespace) -> str:
    """Return the PEM text from --file or by downloading --url."""
    if args.file:
        with open(args.file, "r", encoding="utf-8") as fh:
            return fh.read()
    with urllib.request.urlopen(args.url, timeout=30) as resp:  # noqa: S310 (https only)
        return resp.read().decode("utf-8")


def count_certs(pem: str) -> int:
    """Count the number of certificates in a PEM blob."""
    return pem.count("-----BEGIN CERTIFICATE-----")


def render_header(pem: str, source: str) -> str:
    """Render the RootCABundle.h contents embedding the PEM as a raw string."""
    if "PEM_DELIM" in pem:
        # Practically impossible, but guard the raw-string delimiter anyway.
        raise ValueError("PEM contains the raw-string delimiter; aborting")
    n = count_certs(pem)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return f"""// EdgeLLM — default root CA bundle (GENERATED FILE — DO NOT EDIT BY HAND).
//
// Generated by tools/gen_ca_bundle.py
//   source:       {source}
//   generated at: {stamp}
//   certificates: {n}
//
// Regenerate periodically (see RUNBOOK.md) to track root rotations.
#ifndef EDGELLM_TRANSPORT_ROOTCABUNDLE_H
#define EDGELLM_TRANSPORT_ROOTCABUNDLE_H

#define EDGELLM_HAS_CA_BUNDLE 1

namespace edge {{

// Stored in flash (.rodata) on embedded targets; directly addressable by the
// platform TLS clients' setCACert()/trust-anchor APIs.
static const char kEdgeLLMRootCABundle[] = R"PEM_DELIM(
{pem}
)PEM_DELIM";

inline const char* defaultCABundle() {{ return kEdgeLLMRootCABundle; }}

}}  // namespace edge

#endif  // EDGELLM_TRANSPORT_ROOTCABUNDLE_H
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default=DEFAULT_URL, help="PEM bundle URL (https only)")
    parser.add_argument("--file", help="use a local PEM file instead of downloading")
    parser.add_argument("--out", default=OUTPUT_PATH, help="output header path")
    args = parser.parse_args()

    if not args.file and not args.url.startswith("https://"):
        print("error: --url must be https", file=sys.stderr)
        return 2

    try:
        pem = load_pem(args).strip()
    except Exception as exc:  # noqa: BLE001 — surface any fetch/read failure clearly
        print(f"error: failed to load PEM: {exc}", file=sys.stderr)
        return 1

    if count_certs(pem) == 0:
        print("error: no certificates found in the PEM source", file=sys.stderr)
        return 1

    source = args.file if args.file else args.url
    header = render_header(pem, source)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(header)

    print(f"wrote {args.out} with {count_certs(pem)} certificate(s) from {source}")
    print("Re-flash your sketch to pick up the new bundle.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
